### ISSUE TITLE
Installation via brew not working

### ISSUE THREAD

**Issue by abhi18av** [typelead/homebrew-eta#1]
Hey, I followed the instructions outlined on this repo's readme but neither `eta` nor `etlas` are in path. The installation via brew seems to have worked fine though as I can see the binary in `/usr/local/Cellar/eta/0.0.6b5 ` folder.

But the executable doesn't have the right permission - something quite unusual for a brew package. Could you help me out, I'm trying to work out the eta tutorial.

**Comment by Abhiroop** [comment]
@abhi18av The `eta` and `etlas` binaries are usually in `~/.local/bin` directory in my machine. Can you try this:
Go to your home directory and then `mkdir -p .local/bin` and then try installing from source? The documentation is here: http://eta-lang.org/docs/html/getting-started.html#installing-eta
The permission for the binaries in my local is `755` you can also try to `chmod 755` the binary and check.

**Comment by abhi18av** [comment]
I've double checked the locations,

```sh

❯ pwd
/Users/eklavya/.local/bin
                                                                
   
❯ ls
ghc-mod                hlint
ghc-modi               hoogle
hasktags               intero
hdevtools              refactor
hindent                stylish-haskell
hindent-generate-tests
                                                                

```


Is XCode really necessary for eta to work? In the meantime I've tried to reinstall the eta languages

```sh
❯ brew uninstall eta
Uninstalling /usr/local/Cellar/eta/0.0.6b5... (9 files, 184KB)
                                                                
   
❯ brew install eta  
Updating Homebrew...
==> Auto-updated Homebrew!
Updated Homebrew from 120985e to 1765062.
Updated 4 taps (caskroom/cask, facebook/fb, homebrew/core, homebrew/science).
==> Updated Formulae
aws-sdk-cpp                      mame
awscli                           mutt
babl                             node
colordiff                        pgpdump
cromwell                         qcachegrind
facebook/fb/buck                 rocksdb
fluent-bit                       rom-tools
freeradius-server                shc
highlight                        tmux
homebrew/science/armadillo       typescript
homebrew/science/opencollada     yle-dl

==> Installing eta from typelead/eta
==> Downloading https://github.com/typelead/eta/archive/0.0.6b5.
Already downloaded: /Users/eklavya/Library/Caches/Homebrew/eta-0.0.6b5.tar.gz
🍺  /usr/local/Cellar/eta/0.0.6b5: 9 files, 184KB, built in 1 second
                                                                
   16s
❯ 
```

**Comment by Abhiroop** [comment]
@abhi18av when you build from source then the binary is installed in `.local/bin` Not when you are installing it using `brew`. This page has documentation on how to build from source: http://eta-lang.org/docs/html/getting-started.html#installing-eta

**Comment by abhi18av** [comment]
Ah, I just assumed that `brew install eta` would take care of everything - since that's how brew packages normally work. 

I'll close the issue then.
